server:
  port: 28928
  servlet:
    context-path: /
spring:
  application:
    name: ai
  datasource:
    url: jdbc:mysql://localhost:3306/ysx-app
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  ai:
    # 基于ollama去拉取模型
    ollama:
      # base-url: http://localhost:11434
      # 彦龙大模型
#      base-url: http://10.244.22.55:11434
      # 部门大模型
      base-url: http://10.244.51.171:8000
      chat:
#       model: deepseek-r1:14b
#        model: deepseek-r1:7b
        model: deepseek-v3_Q4:latest
    # 基于openai去拉取模型
    openai:
      base-url: http://10.244.51.171:8000
      api-key: ollama
      chat:
        options:
          model: deepseek-v3_Q4:latest
        # temperature: 0.7
      embedding:
        options:
          model: bge-m3:567m
          dimensions: 1024
datasource:
  localhost:
    jdbc-url: jdbc:mysql://localhost:3306/ysx-app
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

