server:
  port: 28928
  servlet:
    context-path: /
spring:
  application:
    name: ai
  datasource:
    url: jdbc:mysql://localhost:3306/ysx-app
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 添加文件上传大小限制配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  ai:
    # 基于ollama去拉取模型
    ollama:
      base-url:
      chat:
        model:
    # 基于openai去拉取模型
    openai:
       base-url:
       api-key:
       chat:
         options:
           model:
       embedding:
         options:
           model:
           dimensions:
         base-url:
         api-key:


datasource:
  localhost:
    jdbc-url: jdbc:mysql://localhost:3306/ysx-app
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# 大模型多数据源配置
# 三点五接口： gpt-3.5-turbo
# 四接口/高级：（可用4.0、Claude、Deepseek）
# 4.0系列：gpt-4o(推荐),gpt-image-1(画图),gpt-4.1(新),gpt-4.1-mini(新),gpt-4.1-nano(新),gpt-4,gpt-4o-image(画图),gpt-4o-mini,o3-mini,tts-1,whisper-1,gpt-3.5-turbo
# deepseek系列：deepseek-v3-0324,deepseek-r1(思考),deepseek-v3,deepseek-r1-searching(联网),deepseek-reasoner,deepseek-chat
# Claude系列：claude-3-7-sonnet-20250219,claude-3-7-sonnet-thinking（思考),claude-3-5-sonnet-20241022
# 向量text系列：text-embedding-ada-002（推荐）,text-embedding-3-large,text-embedding-3-small
# grok3系列：grok-3,grok-3-reasoner(思考),grok-3-deepsearch
# gemini系列：gemini-2.5-pro-exp-03-25,gemini-2.0-flash-exp,gemini-2.0-flash-thinking-exp-121

ai:
  openai:
    grok-3:
      base-url:
      api-key:
      model:
      temperature:
      embeddingModelName:
      embeddingDimensions:
    gpt-4o:
      base-url:
      api-key:
      model:
      temperature:
      embeddingModelName:
      embeddingDimensions:

  ollama:
    deepseek:
      base-url: http://localhost:11434
      model: deepseek-r1:14B
      temperature: 0.7
    qwen3:
      base-url: http://localhost:11434
      model: qwen3:14b
      temperature: 0.5
    deepseek-v3_Q4:latest:
      base-url: http://10.244.51.171:8000
      model: deepseek-v3_Q4:latest
      temperature: 0.7
    deepseek-r1:7b:
      base-url: http://10.244.22.55:11434
      model: deepseek-r1:7b
      temperature: 0.9